# Site settings
name: Interaction Design
title: BDes (Hons) Interaction Design
email: info@ixdbelfast.org
description: "BDes (Hons) Interaction Design, Belfast School of Art."
keywords: "interaction design, belfast, school of art, university of ulster"
baseurl: ""
homeurl: "/"
url: "http://ixdbelfast.org"

# Authors
authors:
  chris:
    name: Christopher Murphy
    avatar: https://pbs.twimg.com/profile_images/3363977232/3719860c3f790ed9b16e25868caf2295.jpeg
    position: Senior Lecturer
    email: chris.murphy@ulster.ac.uk
    web: http://monographic.org/
    twitter: https://twitter.com/fehler
  paul:
    name: Paul McCormack
    avatar: https://avatars3.githubusercontent.com/u/6138096?s=400
    position: Lecturer
    email: p.mccormack@ulster.ac.uk
    web: http://pixelpaper.github.io
    twitter: https://twitter.com/eleventhirty
  kyle:
    name: Dr Kyle Boyd
    avatar: https://pbs.twimg.com/profile_images/477017698761990144/s779Nozc_400x400.jpeg
    position: Lecturer
    email: ka.boyd@ulster.ac.uk
    web: http://www.kyleboyd.co.uk
    twitter: https://twitter.com/kylbyd

# Google Analytics
ua: "51233441-1"

# Social
social: "ixdbelfast"

# Build settings
markdown: kramdown
permalinks: pretty
